openapi: "3.0.3"

info:
  version: 1.0.0
  title: SA Liabilities Payment Details API

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production

components:
  headers:
    correlationId:
      description: Unique Transaction Reference
      schema:
        type: string
        format: uuid

  securitySchemes:
    User-Restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [User-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:self-assessment: Grant read access

  parameters:
    nino:
      name: NINO
      in: path
      description: The National Insurance Number sent with the subject of the request
      schema:
        type: string
        pattern: '^[A-Z]{2}[0-9]{6}[A-Z]$'
      required: true

  schemas:
    BalanceDetail:
      type: object
      properties:
        payableAmount:
          type: number
          format: double
          description: |
            The sum of 'chargeAmount' for all charges where:
            - The 'nino' matches the provided path parameter.
            - The 'chargeAmount' is not zero.
            - The 'chargeDueDate' is within 30 days (i.e., payable).
          minimum: -99999999999.99
          maximum: 99999999999.99
        payableDueDate:
          type: string
          format: date
          description: |
              The earliest 'chargeDueDate' found against the payable charges
              Format: YYYY-MM-DD.
        pendingDueAmount:
          type: number
          format: double
          description: |
            The sum of 'chargeAmount' for all charges where:
            - The 'nino' matches that provided in the path parameter;  
            - The 'chargeAmount' is not zero;  
            - The 'chargeDueDate' is due in 30 days or more (i.e., pending)
          minimum: -99999999999.99
          maximum: 99999999999.99
        pendingDueDate:
          type: string
          format: date
          description: |
              The earliest 'chargeDueDate' found against the pending charges
              Format: YYYY-MM-DD.
        overdueAmount:
          type: number
          format: double
          description: |
            The sum of 'chargeAmount' for all charges where:
            - The 'nino' matches that provided in the path parameter; 
            - The 'chargeAmount' is not zero; 
            - The 'chargeDueDate' is in the past
          minimum: -99999999999.99
          maximum: 99999999999.99
        totalBalance:
          type: number
          format: double
          description: The sum of 'payableAmount', 'pendingDueAmount', and 'overdueAmount'
          minimum: -99999999999.99
          maximum: 99999999999.99
      required:
        - payableAmount
        - pendingDueAmount
        - overdueAmount

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: "Enumerated Error Code - 4x numerical characters"
          enum:
            - "1002"
            - "1113"
        errorDescription:
          type: string
          description: "Description of the error covered by the Enum code"
          enum:
            - "NINO not found"
            - "Invalid path parameters"
      required:
        - errorCode
        - errorDescription
      example:
        errorCode: "1002"
        errorDescription: "NINO not found"

paths:
  /payments/self-assessment/liabilities/nino/{NINO}:
    get:
      summary: Get SA liabilities payment details
      parameters:
        - $ref: '#/components/parameters/nino'
      responses:
        '200':
          description: SA Liabilities payment details
          content:
            application/json:
              schema:
                type: object
                properties:
                  balanceDetails:
                    type: array
                    items:
                      $ref: '#/components/schemas/BalanceDetail'
              example:
                balanceDetails:
                  - payableAmount: 1500.00
                    payableDueDate: "2024-09-01"
                    pendingDueAmount: 2500.00
                    pendingDueDate: "2024-10-01"
                    overdueAmount: 500.00
                    totalBalance: 4500.00
        '400':
          description: Invalid request parameters or NINO not found
          headers:
            correlationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - User-Restricted:
            - read:self-assessment
